name: Build and push Docker images

on: [push] 

jobs:
  push-image:

    runs-on: windows-latest

    steps:
     -  uses: actions/checkout@v2
     - run: |
        ls ~
        dir
        docker build -t storedev/store-bot:${{ github.sha }} .
        docker push storedev/store-bot:${{ github.sha }}
