name: docker

on: [push] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
            -t $DOCKER_IMAGE_NAME \
            --output "type=image,push=true" \
            --platform $DOCKER_PLATFORMS .
        env:
          DOCKER_IMAGE_NAME: storedev/store-bot:latest
          DOCKER_PLATFORMS: linux/amd64,linux/arm64,linux/arm
